name: "📚 Blog Updater"

on:
    workflow_dispatch:
    schedule:
        - cron: "* 7 * * *" # Runs Every 24 Hours

jobs:
    update_blogs:
        name: "Update Blogs"
        runs-on: ubuntu-latest
        steps:
            - name: "📥  Fetching Blog Contents"
              uses: actions/checkout@main

            - name: "📚  Hashnode Updater"
              uses: "varunsridharan/action-hashnode-blog@1.1.1"
              with:
                  USERNAME: "psypher1" # Hashnode Username
                  COUNT: 3 # MAX Visisble
                  STYLE: "blog-left"
                  BLOG_URL: "https://dantedecodes.hashnode.dev/"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
